[package]
name = "depot-rs"
version = "0.1.0"
description = "A TUI for managing your crates."
authors = ["pigeon <pigeon@quietpigeon.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
